const lineBreak = document.createElement('br');
const optionsForClock = ['Dark/Light Mode', 'Show/hide Digital time', 'Show/hide seconds', 'Show/Hide second hand'];
const optionsForTimer = ['Dark/Light Mode'];
const optionsForAlarm = ['Dark/Light Mode'];
const optionsForAdd = ['Add new clock', 'Add new timer', 'Add new alarm', 'Clear all'];
const optionsForSnooze = ['for 1 minutes', 'for 5 minutes', 'for 10 minutes'];
var options = {timeZone: ''};
const alarmSound = new Audio("C:\\My learnings\\AnalogClock\\mixkit-facility-alarm-sound-999.wav");
alarmSound.loop = true;
const parent = document.getElementsByClassName('parent')[0];
const currentWeatherPath = 'http://api.openweathermap.org/data/2.5/weather?q=';
const forecastWeatherPath = 'http://api.openweathermap.org/data/2.5/forecast?q=';
const apiKey = '&APPID=001b0f58045147663b1ea518d34d88b4';
const units = '&units=metric';
const citiesInIndia = ['Srinagar', 'Delhi', 'Ahmedabad', 'Shimla', 'Mumbai', 'Goa', 'Bangalore', 'Hyderabad', 'Ooty', 'Kodaikanal', 'Chennai', 'Thiruvananthapuram', 'Kochi'];
const citiesInNewYork = ['Albany', 'Brooklyn', 'Staten Island', 'Bronx', 'Williamsburg', 'Beacon', 'Manhattan', 'Washington', 'Hamburg', 'Lake Placid', 'Rochester'];
const citiesInLosAngeles = ['Santa Clarita', 'Downey', 'El Monte', 'Hidden Hills', 'Lakewood', 'Maywood', 'Montebello', 'Norwalk', 'Palmdale', 'San Marino', 'Walunt', 'Whittier'];
const citiesInLondon = ['Greenwich', 'Westminster', 'Islington', 'Marylebone', 'Feltham', 'Clerkenwell', 'Barking', 'Hounslow', 'Acton', 'Dagenham', 'Sutton', 'Harrow'];
const citiesInJapan = ['Tokyo', 'Osaka', 'Yokohama', 'Nagoya', 'Kyoto', 'Sapporo', 'Kobe', 'Kawasaki', 'Saitama', 'Fukuoka', 'Hokkaido', 'Furano', 'Hiroshima', 'Nara', 'Himeji'];
const citiesInChina = ['Shangai', 'Beijing', 'Hong Kong', 'Taipei', 'Canton', 'Macau', 'Chengdu', 'Xian', 'Guangzhou', 'Shenzhen', 'Chongqing', 'Tianjin', 'Wuhan', 'Sanya'];